///////////////////////////////////////////////////////////////////////////////
// VersionedProjectInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "VersionedProjectServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
