///////////////////////////////////////////////////////////////////////////////
// VersionedProjectServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_VersionedProject = 0x3F000000;
#define SRVNAME_VERSIONEDPROJECT "VersionedProject"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_VersionedProjectCCyclicModule = {0x3b7be2e3,0x98c5,0x4c18,{0x83,0x70,0x9a,0xa6,0x4c,0x67,0xbb,0x93}};
const CTCID CID_VersionedProjectCSentinel = {0x9aa91308,0x603f,0x488d,{0xad,0x8f,0x95,0x85,0xe8,0xc9,0xa0,0xb5}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_CyclicModuleParameter = 0x00000001;
const PTCID PID_SentinelTaskB = 0x00000001;
const PTCID PID_SentinelTaskC = 0x00000002;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_B94B4108_4081_4916_81A4_6642B01C2ACF_INCLUDED_)
#define _TC_TYPE_B94B4108_4081_4916_81A4_6642B01C2ACF_INCLUDED_
typedef struct _TData
{
	ULONGLONG cnt;
} TData, *PTData;
#endif // !defined(_TC_TYPE_B94B4108_4081_4916_81A4_6642B01C2ACF_INCLUDED_)

typedef struct _CyclicModuleParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} CyclicModuleParameter, *PCyclicModuleParameter;

#pragma pack(push,1)
typedef struct _CyclicModuleInputs
{
	bool bExceed;
} CyclicModuleInputs, *PCyclicModuleInputs;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_CyclicModuleInputs 0
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
